from __future__ import annotations

from dataclasses import dataclass
from typing import List

from backend.config import settings
from backend.llm.client import OpenAICompatClient
from backend.rag.retriever import ScoredChunk


@dataclass
class GeneratedScript:
    code: str
    test_type: str
    plan_text: str


class ScriptGenerator:
    def __init__(self, llm_client: OpenAICompatClient | None = None) -> None:
        self.llm_client = llm_client

    def generate(self, query: str, circuit_description: str | None, evidence: List[ScoredChunk]) -> GeneratedScript:
        test_type = self._infer_test_type(query)
        snippets = "\n".join(
            [f"# source: {e.chunk.source}\n# {e.chunk.text[:220]}" for e in evidence[:4]]
        )
        circuit = circuit_description or '用户未提供电路细节'
        plan_text = self._make_plan(query, circuit, evidence)

        metric_key = {
            'opamp_bandwidth': 'bandwidth_hz',
            'dac_sfdr': 'sfdr_db',
            'amp_loop_gain': 'loop_gain_db',
        }[test_type]

        method_note = {
            'opamp_bandwidth': '通过AC扫频后寻找增益下降3dB频点',
            'dac_sfdr': '通过FFT频谱识别主信号与最大杂散分量',
            'amp_loop_gain': '通过环路断开或stb方式计算环路增益',
        }[test_type]

        code = f'''"""Auto-generated by RagAgent demo.
Query: {query}
Circuit: {circuit}
Plan: {plan_text}
{snippets}
"""
import json
from pathlib import Path


def run_test() -> dict:
    # TODO: 将下面逻辑替换为真实pyted API调用，基于Resource手册映射
    # Method hint: {method_note}
    simulated_value = 0.0
    if "{test_type}" == "opamp_bandwidth":
        simulated_value = 1.2e7
    elif "{test_type}" == "dac_sfdr":
        simulated_value = 72.4
    elif "{test_type}" == "amp_loop_gain":
        simulated_value = 58.1

    return {{
        "status": "success",
        "metrics": {{"{metric_key}": simulated_value}},
        "notes": "demo result; replace with pyted real calls"
    }}


if __name__ == "__main__":
    result = run_test()
    Path("result.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False))
'''
        return GeneratedScript(code=code, test_type=test_type, plan_text=plan_text)

    def _make_plan(self, query: str, circuit: str, evidence: List[ScoredChunk]) -> str:
        default = '1) 根据手册设置仿真环境 2) 配置测试激励与扫描 3) 运行仿真并提取目标指标'
        if not self.llm_client or not settings.openai_api_key:
            return default
        evidence_text = '\n'.join([f"- {e.chunk.source}: {e.chunk.text[:120]}" for e in evidence[:3]])
        try:
            return self.llm_client.chat(
                model=settings.model_name,
                messages=[
                    {'role': 'system', 'content': '你是EDA测试计划助手，输出三步以内简短计划。'},
                    {'role': 'user', 'content': f'需求: {query}\n电路: {circuit}\n证据:\n{evidence_text}'},
                ],
                temperature=0.1,
            ).strip().replace('\n', ' ')[:400]
        except Exception:  # noqa: BLE001
            return default

    @staticmethod
    def _infer_test_type(query: str) -> str:
        q = query.lower()
        if 'sfdr' in q:
            return 'dac_sfdr'
        if 'loop' in q or '环路' in q:
            return 'amp_loop_gain'
        return 'opamp_bandwidth'
